
# TOPVISOR
@authToken = 11b01aac035046e19c646a3a8532ef8e
@userID = 359112

# GET https://api.topvisor.com/v2/json/get/projects_2/projects HTTP/1.1
# User-Id:{{userID}}
# Authorization:{{authToken}}

###
GET http://localhost:3000/api/topvisor/projects HTTP/1.1



### get positions
GET http://localhost:3000/api/topvisor/positions?project_id=7784199&regions_indexes=88&regions_indexes=152&date1=2023-06-27&date2=2023-07-06 HTTP/1.1




# YANDEX 

@OAuthToken = 'OAuth y0_AgAAAABu9NRrAAomKAAAAADnMtO185qHccw3TkWlYwQonI26xu0sFTg'


###
GET http://localhost:3000/api/yandex/projects?search_string=94156620 HTTP/1.1


### dashboards device
GET  http://localhost:3000/api/yandex/dashboards/visits?date1=2023-06-07&date2=2023-07-07&ids=12418261 HTTP/1.1






# GENERAL

### get projects
GET http://localhost:3000/api/general/projects?search_string=gitddhub HTTP/1.1




