# yandex get all users from specific team
GET http://localhost:3000/api/yandex/dashboards/goal-dimension?date1=2023-07-16&date2=2023-07-16T23:00:00.000Z&ids=12418261







# topvisor
###
GET http://localhost:3000/api/topvisor/positions/?project_id=7784199&regions_indexes=152&regions_indexes=88&date1=2023-06-12&date2=2023-07-12

###
GET http://localhost:3000/api/topvisor/fetch/projects




# general
###
GET http://localhost:3000/api/general/update-db